name: consultancy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.0
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.1.4
  crypto: ^3.0.3
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  biometric_storage: ^5.0.1
  local_auth: ^2.1.7



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/login_page.webp
    - assets/logo.png
    - assets/registeration.png
