// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe8D93PyIMS8jV_hq39nQkvS9jxPVDCbM',
    appId: '1:237099479999:web:26a942094e1de5c280a70a',
    messagingSenderId: '237099479999',
    projectId: 'ssm-consultancy',
    authDomain: 'ssm-consultancy.firebaseapp.com',
    databaseURL: 'https://ssm-consultancy-default-rtdb.firebaseio.com',
    storageBucket: 'ssm-consultancy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw8KvUkuSV-gBTjEQqJv27AFlck0XPTIA',
    appId: '1:237099479999:android:07070b0fcf942a9080a70a',
    messagingSenderId: '237099479999',
    projectId: 'ssm-consultancy',
    databaseURL: 'https://ssm-consultancy-default-rtdb.firebaseio.com',
    storageBucket: 'ssm-consultancy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb2K0lq2lM15ahgY1Gfx6QFylufFhqPiA',
    appId: '1:237099479999:ios:35cd402707f916a980a70a',
    messagingSenderId: '237099479999',
    projectId: 'ssm-consultancy',
    databaseURL: 'https://ssm-consultancy-default-rtdb.firebaseio.com',
    storageBucket: 'ssm-consultancy.firebasestorage.app',
    iosBundleId: 'com.example.consultancy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb2K0lq2lM15ahgY1Gfx6QFylufFhqPiA',
    appId: '1:237099479999:ios:35cd402707f916a980a70a',
    messagingSenderId: '237099479999',
    projectId: 'ssm-consultancy',
    databaseURL: 'https://ssm-consultancy-default-rtdb.firebaseio.com',
    storageBucket: 'ssm-consultancy.firebasestorage.app',
    iosBundleId: 'com.example.consultancy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe8D93PyIMS8jV_hq39nQkvS9jxPVDCbM',
    appId: '1:237099479999:web:54fa9022e67d5ecb80a70a',
    messagingSenderId: '237099479999',
    projectId: 'ssm-consultancy',
    authDomain: 'ssm-consultancy.firebaseapp.com',
    databaseURL: 'https://ssm-consultancy-default-rtdb.firebaseio.com',
    storageBucket: 'ssm-consultancy.firebasestorage.app',
  );
}
